# Hospital Management System AI Configuration

# Database Configuration
database:
  host: localhost
  port: 5432
  name: hospital_management
  user: postgres
  password: your_password
  pool_size: 20
  max_overflow: 30

# AI Model Configuration
ai_models:
  diagnosis:
    model_path: "data/models/diagnosis_model.pkl"
    confidence_threshold: 0.8
    max_predictions: 5
  
  risk_assessment:
    model_path: "data/models/risk_model.pkl"
    risk_threshold: 0.7
  
  recommendations:
    model_path: "data/models/recommendation_model.pkl"
    max_recommendations: 10

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  workers: 4
  timeout: 30

# Security Configuration
security:
  secret_key: "your-secret-key-here"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7

# External APIs
external_apis:
  openai:
    api_key: "your-openai-api-key"
    model: "gpt-4"
    max_tokens: 1000
  
  pubmed:
    api_key: "your-pubmed-api-key"
    base_url: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
  
  drugbank:
    api_key: "your-drugbank-api-key"
    base_url: "https://api.drugbank.com/v1/"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/ai_service.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Monitoring Configuration
monitoring:
  prometheus_port: 9090
  health_check_interval: 30
  metrics_interval: 60

# Cache Configuration
cache:
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 0
  ttl: 3600  # 1 hour

# Hospital Management System Integration
hms_integration:
  api_url: "http://localhost:3001/api"
  websocket_url: "ws://localhost:3001/ws"
  auth_token: "your-hms-auth-token"
