[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[deploy.envs]
NODE_ENV = "production"
REACT_APP_API_URL = "https://hospital-backend-production-0e2e.up.railway.app"
REACT_APP_AI_SERVICE_URL = "https://hospital-ai-production-xxxx.up.railway.app" 