services:
  - type: web
    name: hospital-ai-service
    env: docker
    plan: free
    branch: main
    rootDir: python-ai-project
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: PUBMED_API_KEY
        sync: false
      - key: FDA_API_KEY
        sync: false
      - key: PORT
        value: 8000
    buildCommand: ""
    startCommand: ""

  - type: web
    name: hospital-backend
    env: docker
    plan: free
    branch: main
    rootDir: backend
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: AI_SERVICE_URL
        value: https://hospital-ai-service.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    buildCommand: ""
    startCommand: ""

  - type: web
    name: hospital-frontend
    env: docker
    plan: free
    branch: main
    rootDir: .
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3003
      - key: REACT_APP_API_URL
        value: https://hospital-backend-g0oi.onrender.com/api
      - key: REACT_APP_AI_SERVICE_URL
        value: https://hospital-ai-service.onrender.com
    buildCommand: ""
    startCommand: "" 