services:
  - type: web
    name: hospital-ai-service
    env: docker
    plan: free
    branch: main
    rootDir: python-ai-project
    dockerfilePath: python-ai-project/Dockerfile
    healthCheckPath: /
    envVars:
      - key: PUBMED_API_KEY
        sync: false
      - key: FDA_API_KEY
        sync: false
      - key: PORT
        value: 8000

  - type: web
    name: hospital-backend
    env: docker
    plan: free
    branch: main
    rootDir: backend
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      # Add your DB and other secrets here

  - type: web
    name: hospital-frontend
    env: docker
    plan: free
    branch: main
    rootDir: .
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3003 