services:
  # Backend Service (Node.js)
  - type: web
    name: hospital-backend
    env: node
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: AI_SERVICE_URL
        value: https://hospital-ai-service.onrender.com

  # Frontend Service (React)
  - type: web
    name: hospital-frontend
    env: node
    plan: free
    branch: main
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000
    healthCheckPath: /
    envVars:
      - key: REACT_APP_API_URL
        value: https://hospital-backend.onrender.com
      - key: REACT_APP_AI_API_URL
        value: https://hospital-ai-service.onrender.com
      - key: PORT
        value: 3000

  # AI Service (Python FastAPI) - Full Enhanced Version with Auto-Training
  - type: web
    name: hospital-ai-service
    env: python
    plan: free
    branch: main
    rootDir: python-ai-project
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn enhanced_medical_api:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PUBMED_API_KEY
        sync: false
      - key: FDA_API_KEY
        sync: false
      - key: PORT
        value: 8000 