services:
  # AI Service
  - type: web
    name: hospital-ai-service
    env: docker
    rootDir: python-ai-project
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 8000
      - key: AUTO_TRAIN_ON_STARTUP
        value: "true"
      - key: PUBMED_API_KEY
        sync: false
      - key: FDA_API_KEY
        sync: false

  # Backend Service
  - type: web
    name: hospital-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: AI_SERVICE_URL
        value: https://hospital-ai-service.onrender.com

  # Frontend Service
  - type: web
    name: hospital-frontend
    env: docker
    rootDir: .
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 3003
      - key: REACT_APP_API_URL
        value: https://hospital-backend.onrender.com/api 