[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node --max-old-space-size=512 --expose-gc server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production" 